/**
 * inference_impl.h  —  NetWeights struct + forward() implementation.
 *
 * Include AFTER weights.h:
 *   #include "weights.h"
 *   #include "inference.h"
 *   #include "inference_impl.h"
 *
 * weights.h is generated by tools/export_weights.py and contains
 * all float arrays with the naming convention:
 *   w_stem_0_weight, w_stem_1_weight, w_stem_1_bias, etc.
 */

#pragma once
#include "inference.h"
#include <vector>
#include <cstring>

namespace sofcon_nn {

// Scratch buffer pool (stack-like, avoids repeated malloc)
struct Scratch {
    std::vector<float> buf;
    Scratch(int n) : buf(n, 0.f) {}
    float* get(int offset = 0) { return buf.data() + offset; }
};

// ------------------------------------------------------------------ //
//  ResBlock forward
// ------------------------------------------------------------------ //
static void res_block_forward(
    const float* x, int C, int H, int W,
    // conv1 weight/BN params
    const float* c1w,
    const float* b1g, const float* b1b, const float* b1m, const float* b1v,
    // conv2 weight/BN params
    const float* c2w,
    const float* b2g, const float* b2b, const float* b2m, const float* b2v,
    float* out, float* tmp1, float* tmp2)
{
    int chw = C * H * W;

    // conv1 → BN1 → ReLU
    conv2d(x,    C, H, W, c1w, C, 3, 3, nullptr, tmp1);
    batch_norm(tmp1, C, H, W, b1g, b1b, b1m, b1v, BN_EPS, tmp2);
    relu_inplace(tmp2, chw);

    // conv2 → BN2
    conv2d(tmp2, C, H, W, c2w, C, 3, 3, nullptr, tmp1);
    batch_norm(tmp1, C, H, W, b2g, b2b, b2m, b2v, BN_EPS, out);

    // residual + ReLU
    add_relu(out, x, chw);
}

// ------------------------------------------------------------------ //
//  Full forward pass  (uses weights.h symbols directly)
// ------------------------------------------------------------------ //
void forward(const float* board_input, int C_in, int H, int W,
             const NetWeights& /*wt — unused, we use globals from weights.h*/,
             float* policy_out, float& value_out)
{
    int hw  = H * W;
    int chw = CH * hw;

    // allocate scratch
    std::vector<float> a(chw), b(chw), c(chw), d(chw);
    float* cur  = a.data();
    float* tmp1 = b.data();
    float* tmp2 = c.data();
    float* res  = d.data();

    // ---- Stem ----
    // Conv(C_in → CH, 3x3, pad=1)
    conv2d(board_input, C_in, H, W,
           w_stem_0_weight, CH, 3, 3, nullptr, tmp1);
    // BN + ReLU
    batch_norm(tmp1, CH, H, W,
               w_stem_1_weight, w_stem_1_bias,
               w_stem_1_running_mean, w_stem_1_running_var,
               BN_EPS, cur);
    relu_inplace(cur, chw);

    // ---- ResBlocks ----
#define RES(i) \
    res_block_forward(cur, CH, H, W, \
        w_blocks_##i##_conv1_weight, \
        w_blocks_##i##_bn1_weight, w_blocks_##i##_bn1_bias, \
        w_blocks_##i##_bn1_running_mean, w_blocks_##i##_bn1_running_var, \
        w_blocks_##i##_conv2_weight, \
        w_blocks_##i##_bn2_weight, w_blocks_##i##_bn2_bias, \
        w_blocks_##i##_bn2_running_mean, w_blocks_##i##_bn2_running_var, \
        res, tmp1, tmp2); \
    std::swap(cur, res);

    RES(0) RES(1) RES(2)
#undef RES

    // ---- Policy head ----
    {
        std::vector<float> ph(2*hw);
        conv2d(cur, CH, H, W, w_policy_conv_weight, 2, 1, 1, nullptr, tmp1, 0, 1);
        batch_norm(tmp1, 2, H, W,
                   w_policy_bn_weight, w_policy_bn_bias,
                   w_policy_bn_running_mean, w_policy_bn_running_var,
                   BN_EPS, ph.data());
        relu_inplace(ph.data(), 2*hw);
        linear(ph.data(), 2*hw, w_policy_fc_weight, w_policy_fc_bias,
               policy_out, hw);
        softmax(policy_out, hw);
    }

    // ---- Value head ----
    {
        std::vector<float> vh(hw), vh2(256);
        conv2d(cur, CH, H, W, w_value_conv_weight, 1, 1, 1, nullptr, tmp1, 0, 1);
        batch_norm(tmp1, 1, H, W,
                   w_value_bn_weight, w_value_bn_bias,
                   w_value_bn_running_mean, w_value_bn_running_var,
                   BN_EPS, vh.data());
        relu_inplace(vh.data(), hw);
        linear(vh.data(), hw, w_value_fc1_weight, w_value_fc1_bias, vh2.data(), 256);
        relu_inplace(vh2.data(), 256);
        float vscalar;
        // read only value[0] = current player's win-prob (layout: [MAX_PLAYERS, 256])
        linear(vh2.data(), 256, w_value_fc2_weight, w_value_fc2_bias, &vscalar, 1);
        value_out = 1.0f / (1.0f + std::exp(-vscalar));  // sigmoid, matches Python
    }
}

} // namespace sofcon_nn
