/**
 * inference.h  —  Zero-dependency neural network inference for SofconNet.
 *
 * Include this header + weights.h (generated by tools/export_weights.py)
 * in your submission file.  No external libraries required.
 *
 * Architecture mirrors model/network.py exactly:
 *   Stem Conv(c_in→64, 3x3) + BN + ReLU
 *   5x ResBlock(64)
 *   Policy head: Conv(64→2,1x1)+BN+ReLU → FC(2*H*W → H*W) → Softmax
 *   Value  head: Conv(64→1,1x1)+BN+ReLU → FC(H*W→256)+ReLU → FC(256→1)+Tanh
 */

#pragma once
#include <cmath>
#include <cstring>
#include <algorithm>
#include <vector>

namespace sofcon_nn {

// ------------------------------------------------------------------ //
//  Basic math helpers
// ------------------------------------------------------------------ //

static inline float relu(float x) { return x > 0.f ? x : 0.f; }
static inline float fast_tanh(float x) {
    // accurate enough for inference
    if (x >  4.f) return  1.f;
    if (x < -4.f) return -1.f;
    float x2 = x * x;
    return x * (27.f + x2) / (27.f + 9.f * x2);
}

// ------------------------------------------------------------------ //
//  Tensor helpers  (row-major, no heap except caller-provided buffers)
// ------------------------------------------------------------------ //

// out[oc, oh, ow] = sum_{ic,kh,kw} in[ic, oh+kh, ow+kw] * w[oc,ic,kh,kw] + b[oc]
// in_data : (C_in,  H,  W)
// w       : (C_out, C_in, kH, kW)
// b       : (C_out,) or nullptr
// out     : (C_out, H_out, W_out)  — caller allocates
static void conv2d(
    const float* in_data, int C_in,  int H,   int W,
    const float* w,       int C_out, int kH,  int kW,
    const float* b,
    float* out,
    int pad = 1, int stride = 1)
{
    int H_out = (H + 2*pad - kH) / stride + 1;
    int W_out = (W + 2*pad - kW) / stride + 1;

    for (int oc = 0; oc < C_out; ++oc) {
        for (int oh = 0; oh < H_out; ++oh) {
            for (int ow = 0; ow < W_out; ++ow) {
                float sum = b ? b[oc] : 0.f;
                for (int ic = 0; ic < C_in; ++ic) {
                    for (int kh = 0; kh < kH; ++kh) {
                        for (int kw = 0; kw < kW; ++kw) {
                            int ih = oh*stride - pad + kh;
                            int iw = ow*stride - pad + kw;
                            if (ih < 0 || ih >= H || iw < 0 || iw >= W) continue;
                            int in_idx  = (ic*H + ih)*W + iw;
                            int w_idx   = ((oc*C_in + ic)*kH + kh)*kW + kw;
                            sum += in_data[in_idx] * w[w_idx];
                        }
                    }
                }
                out[(oc*H_out + oh)*W_out + ow] = sum;
            }
        }
    }
}

// Batch-norm (inference mode, no running stats update)
// x, out: (C, H, W)  gamma/beta/mean/var: (C,)
static void batch_norm(
    const float* x, int C, int H, int W,
    const float* gamma, const float* beta,
    const float* running_mean, const float* running_var,
    float eps, float* out)
{
    int hw = H * W;
    for (int c = 0; c < C; ++c) {
        float scale = gamma[c] / std::sqrt(running_var[c] + eps);
        float shift = beta[c] - running_mean[c] * scale;
        const float* src = x   + c * hw;
        float*       dst = out + c * hw;
        for (int i = 0; i < hw; ++i)
            dst[i] = src[i] * scale + shift;
    }
}

// in-place relu on (C,H,W) tensor
static void relu_inplace(float* x, int n) {
    for (int i = 0; i < n; ++i) x[i] = relu(x[i]);
}

// residual add: out[i] += x[i], then relu
static void add_relu(float* out, const float* x, int n) {
    for (int i = 0; i < n; ++i) out[i] = relu(out[i] + x[i]);
}

// FC: out[j] = sum_i in_data[i]*w[j*in_features+i] + b[j]
static void linear(
    const float* in_data, int in_features,
    const float* w, const float* b,
    float* out, int out_features)
{
    for (int j = 0; j < out_features; ++j) {
        float s = b ? b[j] : 0.f;
        const float* row = w + j * in_features;
        for (int i = 0; i < in_features; ++i) s += in_data[i] * row[i];
        out[j] = s;
    }
}

static void softmax(float* x, int n) {
    float mx = *std::max_element(x, x+n);
    float sum = 0.f;
    for (int i = 0; i < n; ++i) { x[i] = std::exp(x[i] - mx); sum += x[i]; }
    for (int i = 0; i < n; ++i) x[i] /= sum;
}

// ------------------------------------------------------------------ //
//  Network config (must match training)
// ------------------------------------------------------------------ //
static const int CH    = 64;   // trunk channels
static const int NBLK  = 5;    // ResBlocks
static const float BN_EPS = 1e-5f;

// ------------------------------------------------------------------ //
//  Forward pass
//  board_input: (C_in, H, W) float array (caller fills)
//  policy_out : (H*W,) float  — softmax probabilities
//  value_out  : scalar float  — win estimate in (-1,1)
// ------------------------------------------------------------------ //
struct NetWeights; // forward declaration — defined in weights.h

void forward(const float* board_input, int C_in, int H, int W,
             const NetWeights& wt,
             float* policy_out, float& value_out);

} // namespace sofcon_nn
