"""
Export trained PyTorch weights to a C++ header file.
The header contains all weight/bias arrays as plain float[] literals,
enabling zero-dependency inference in C++.

Usage:
    python tools/export_weights.py --checkpoint model/checkpoint.pt \
                                   --output cpp/weights.h
"""

import torch
import numpy as np
import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(__file__)))
from model.network import SofconNet


def export(checkpoint_path: str, output_path: str):
    ckpt = torch.load(checkpoint_path, map_location="cpu")
    state = ckpt["model"] if "model" in ckpt else ckpt

    lines = []
    lines.append("// AUTO-GENERATED by tools/export_weights.py — do not edit")
    lines.append("#pragma once")
    lines.append("#include <cstddef>")
    lines.append("")

    var_map = {}  # pytorch key -> C identifier

    for key, tensor in state.items():
        arr = tensor.cpu().numpy().astype(np.float32)
        cname = "w_" + key.replace(".", "_").replace("-", "_")
        var_map[key] = cname

        flat = arr.flatten()
        shape_comment = "x".join(str(s) for s in arr.shape)
        lines.append(f"// {key}  shape: {shape_comment}")
        lines.append(f"static const float {cname}[{flat.size}] = {{")

        # write 8 values per line
        for i in range(0, len(flat), 8):
            chunk = flat[i:i+8]
            row = ", ".join(f"{v:.8e}f" for v in chunk)
            lines.append(f"    {row},")
        lines.append("};")
        lines.append("")

    # emit shape metadata
    lines.append("// Shape metadata")
    for key, tensor in state.items():
        cname = var_map[key]
        shape = list(tensor.shape)
        shape_str = ", ".join(str(s) for s in shape)
        ndim = len(shape)
        lines.append(f"static const int {cname}_shape[{ndim}] = {{{shape_str}}};")
    lines.append("")

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print(f"Exported {len(var_map)} tensors to {output_path}")


if __name__ == "__main__":
    p = argparse.ArgumentParser()
    p.add_argument("--checkpoint", default="model/checkpoint.pt")
    p.add_argument("--output",     default="cpp/weights.h")
    args = p.parse_args()
    export(args.checkpoint, args.output)
